# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('oracle-wifi-manager', ['core', 'wifi'])
    module.includes = '.'
    module.source = [
        'model/oracle-wifi-manager.cc',
        ]

    module_test = bld.create_ns3_module_test_library('oracle-wifi-manager')
    module_test.source = [
        ]

    headers = bld(features='ns3header')
    headers.module = 'oracle-wifi-manager'
    headers.source = [
        'model/oracle-wifi-manager.h'
        ]

    # if bld.env.ENABLE_EXAMPLES:
    #     bld.recurse('examples')

    # bld.ns3_python_bindings()
