#!/usr/bin/python3

import os
import subprocess
from argparse import ArgumentParser


if __name__ == '__main__':
    args = ArgumentParser()
    args.add_argument('-p', type=str)
    args.add_argument('--array', type=str)
    args, script_args = args.parse_known_args()

    if args.array:
        start, stop = tuple(map(int, args.array.split('-')))
        array_ids = range(start, stop + 1)
    else:
        array_ids = range(1)

    env = {'PATH': f'{os.environ.get("PATH")}:.', 'HOME': os.path.expanduser('~')}

    for i in array_ids:
        env['SLURM_ARRAY_TASK_ID'] = str(i)
        output = subprocess.check_output(['bash'] + script_args, env=env)

        with open(f'slurm_{i}.out', 'wb') as file:
            file.write(output)
